[network]
name = "devnet"
stacks_node_rpc_address = "http://localhost:20443"

[accounts.deployer]
mnemonic = "${DEPLOYER_MNEMONIC}"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "<YOUR_MNEMONIC_HERE>"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "<YOUR_MNEMONIC_HERE>"
balance = 100_000_000_000_000
